app_filemanager/urls.py
#coding=utf-8
from django.conf.urls import patterns,url
from app_filemanager import views


urlpatterns=patterns('',
    url(r'^$',views.IndexView, name='index'),
    # create file & project
    url(r'^create/project/$', views.ProjectCreateView.as_view(), name='createproject'),
    url(r'^upload/$', views.UploadView, name='upload'), 
    # list file & project
    url(r'^list/personal/$', views.ListPersonalView, name='listPersonal'),
    url(r'^list/project/$', views.ListProjectView, name='listProject'),
    url(r'^list/allprojectfile/$', views.ListAllProjectFileView, name='listAllProjectFile'),
    url(r'^list/allpublicfile/$', views.ListPublicFileView, name='listPublicFile'),
    # detail file & project
    url(r'^detail/fileid=(?P<file_id>\d+)/$', views.FileDetailView, name='filedetail'), 
    url(r'^detail/fileid_no_edit=(?P<file_id>\d+)/$', views.FileDetailView_no_edit, name='filedetail_no_edit'), 
    url(r'^detail/projectid=(?P<project_id>\d+)/$', views.ProjectDetailView, name='projectdetail'),
    # update file & project
    url(r'^file/update/fileid=(?P<pk>\d+)/$', views.FileUpdateView.as_view(), name='fileupdate'),
    url(r'^project/update/projectid=(?P<pk>\d+)/$', views.ProjectUpdateView.as_view(), name='projectupdate'),
    # list file of each project
    url(r'^list/projectfile/projectid=(?P<project_id>\d+)$', views.ListProjectFileView, name='listProjectfile'),
    # down file
    url(r'^download/fileid=(?P<file_id>\d+)/$',views.DownloadView,name='download'), 
    # delete file
    url(r'^delete/fileid=(?P<pk>\d+)/$', views.DeleteFileView.as_view(), name='deletefile'),
    url(r'search/$',views.SearchView, name='search'), 
)

xtyw/urls.py
from django.conf.urls import patterns, include, url
from app_filemanager import views
# -------------------------------------------------------
from django.contrib import admin
from app_filemanager.api import ProjectResource
entry_resource = ProjectResource()
# -------------------------------------------------------
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    url(r'^$', views.IndexView, name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^api/', include(entry_resource.urls)),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^file/',include('app_filemanager.urls', namespace="file")),
    url(r'^accounts/login/$', 'django.contrib.auth.views.login', name="login"),
    url(r'^accounts/logout$', views.LogoutView, name="logout"),
    url(r'^accounts/profile/$', views.UserProfileView),
)

app_filemanager/models.py
#coding=utf8
from django.db import models
from django.contrib.auth.models import User, Group
from django.db.models import Sum 
from django.template.defaultfilters import slugify
# 类顺序不可改变
class AllProjectManager(models.Manager):
    def get_queryset(self):
        return super(AllProjectManager, self).get_queryset().all()

class CloseProjectManager(models.Manager):
    def get_queryset(self):
        return super(CloseProjectManager, self).get_queryset().filter(public=False)

class PublicProjectManager(models.Manager):
    def get_queryset(self):
        return super(PublicProjectManager, self).get_queryset().filter(public=True)

"""
class PublicProjctManager(models.Manager):
    def get_public_project(self, user):
        return self.get_query_set().filter(user=user, public=True)
# 通过用户获得拥有的且公开的项目，用法：
Project.objects.get_public_project(user=user)
"""
class Project(models.Model):
    name = models.CharField(max_length=50, unique=True)
    public = models.BooleanField(default=True)
    add_date = models.DateTimeField(auto_now_add=True)
    end_data = models.DateTimeField(auto_now=True)
    added_by = models.ForeignKey(User)
    desc = models.TextField(blank=True, null=True)
    # Manager blow:
    allProjects = AllProjectManager()
    closeProjects = CloseProjectManager()
    publicProjects = PublicProjectManager()

    def __unicode__(self):
        return self.name
    class Meta:
        permissions = (
            ('can_edit_project', "能编辑项目"),
            ('can_delete_project', "能删除项目"),
            ('can_add_project', "能添加项目"),
        )

class Tag(models.Model):
    name = models.CharField(max_length=50)
    owner = models.ForeignKey(User)
    def __unicode__(self):
        return self.name

class AllFileManager(models.Manager):
    def get_queryset(self):
        return super(AllFileManager, self).get_queryset().all()
    def get_size_sum(self):
        return super(AllFileManager, self).get_queryset().all().aggregate(Sum('file_size'))


class PrivateFileManager(models.Manager):
    def get_queryset(self):
        return super(PrivateFileManager, self).get_queryset().filter(public=False, deleted=False)
        
class PublicFileManager(models.Manager):
    def get_queryset(self):
        return super(PublicFileManager, self).get_queryset().filter(public=True, deleted=False)

class ProjectFileManager(models.Manager):
    def get_queryset(self):
        return super(ProjectFileManager, self).get_queryset().filter(deleted=False, project__isnull=False)




class File(models.Model):
    def makefilename(instance, filename):
        fname, dot, extension = filename.rpartition('.')
        slug = slugify(fname)
        # 这里的slug会屏蔽掉中文，所以直接用fname
        return '%s.%s' % (fname, extension)
        #return '%s.%s' % (slug, extension)
    #file = models.FileField(upload_to='media')
    file = models.FileField(upload_to=makefilename)
    public = models.BooleanField()# has default
    project = models.ForeignKey(Project, related_name="projects", blank=True, null=True)
    tag = models.ForeignKey(Tag, related_name="tags")
    uploader = models.ForeignKey(User, related_name="users")
    group = models.ManyToManyField(Group, related_name="groups")
    deleted = models.BooleanField()# has default
    desc = models.TextField(blank=True, null=True)
    upload_date = models.DateTimeField(auto_now_add=True)
    change_date = models.DateTimeField(auto_now=True)
    file_size = models.BigIntegerField()
    
    # Managers blow:
    allFiles = AllFileManager()
    privateFiles = PrivateFileManager()
    publicFiles = PublicFileManager()
    projectFiles = ProjectFileManager()    
    

    def __unicode__(self):
        return self.file.name
    def save(self, *args, **kwargs):
        self.file_size = self.file.size
        super(File, self).save(*args, **kwargs)
    class Meta:
        permissions = (
            ("can_edit_file", "能编辑文件"),
            ("can_list_file", "能看文件列表"),
            ("can_delete_file", "能删除文件"),
            ("can_download_file", "能下载文件"),
        )
'''
-----------------------------------------------------------------------------------------------
One-to-many relationships

>>> b = File.objects.get(id=1)
>>> b.projects.all() # Returns all Entry objects related to File.

# b.projects is a Manager that returns QuerySets.
>>> b.projects.filter(headline__contains='一期')
>>> b.projects.count()
-----------------------------------------------------------------------------------------------
Many-to-many relationships

e = Entry.objects.get(id=3)
e.authors.all() # Returns all Author objects for this Entry.
e.authors.count()
e.authors.filter(name__contains='John')

a = Author.objects.get(id=5)
a.entry_set.all() # Returns all Entry objects for this Author.
-----------------------------------------------------------------------------------------------
>>> import copy
>>> manager = MyManager()
>>> my_copy = copy.copy(manager)
------------------------------------------------------------------------------------------------
'''

app_filemanager/views.py
#coding=utf-8
# vim: ai ts=4 sts=4 et sw=4
import datetime
# ----------------------
import sys
reload(sys)
sys.setdefaultencoding('utf-8')
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.shortcuts import render, render_to_response, get_object_or_404, get_list_or_404, HttpResponse
from django.template import RequestContext
from django.http import HttpResponseRedirect
from django.views import generic
from .models import File, Project
from django.contrib.auth.models import User
from .forms import FileForm, ProjectForm
from django.utils import timezone
from django.utils.timezone import utc
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout
from django.core.servers.basehttp import FileWrapper
import mimetypes
@login_required
def IndexView(request):
    activeIndex = "active"
    # 从个人文档中筛选出上传者和当前用户一致的文档
    user_id = request.user.id
    # 所有文档个数
    allFiles = File.allFiles.count()
    # 所有公开文档总量
    publicFiles = File.publicFiles.count()
    # 所有公开文档的大小总和
    allSize = File.allFiles.get_size_sum()
    # 项目个数
    allProjects = Project.allProjects.count()
    # 项目文档数
    projectFiles = File.projectFiles.count()# 项目ID不为空则是项目文件
    #allFiles = File.publicFiles.filter(project__id=u'').count()
    return render_to_response('app_filemanager/index.html', context_instance=RequestContext(request,locals()))

@login_required
def UploadView(request):
    #-----------------------
    #-----------------------
    activeUpload = "active"
    if request.method == 'GET':
        form = FileForm(
            user=request.user,
            initial = {
                'public': '1',
                'deleted': '0',
            },
        )
        return render_to_response('app_filemanager/upload.html', context_instance=RequestContext(request,locals()))
    else:
        form = FileForm(request.user, request.POST, request.FILES)
        if form.is_valid():
            f = File.allFiles.create(
                file = request.FILES['file'],
                public = form.cleaned_data['public'],
                project = form.cleaned_data['project'],
                uploader = User.objects.get(username = request.user.username), 
                deleted = form.cleaned_data['deleted'],
                desc = form.cleaned_data['desc'],
                upload_date = datetime.datetime.now(),
                change_date = datetime.datetime.now(),
                tag = form.cleaned_data['tag'],
            )
            group = form.cleaned_data['group']
            for g in group:
                f.group.add(g)
            f.save()
            return render_to_response('app_filemanager/success.html', context_instance=RequestContext(request,locals()))
        else:
            return render_to_response('app_filemanager/upload.html', context_instance=RequestContext(request,locals()))

def ListPersonalView(request):
    activePersonalList = "active"
    if not request.user.has_perm('app_filemanager.can_list_file'):
        return render_to_response('app_filemanager/noperm.html', context_instance=RequestContext(request,locals()))
    else: 
        user_name = request.user.id
	# {{ new_upload_file }}in template
        privateFiles = File.privateFiles.filter(
            uploader=user_name
        ).order_by('-upload_date')
        
        publicFiles = File.publicFiles.filter(
            uploader=user_name
        ).order_by('-upload_date')
        projectFiles = File.allFiles.filter(
            uploader=user_name,
            project__isnull=False
	# 这里的uploader
        ).order_by('-upload_date')
	    #upload_date__lte = timezone.now()
	    #upload_date__lte = datetime.datetime.utcnow().replace(tzinfo=utc)
    return render_to_response('app_filemanager/listPersonal.html', context_instance=RequestContext(request,locals()))

# -------------------------------list------------------
from django.db.models import Count
def ListProjectView(request):
    activePublicList = "active"
    if not request.user.has_perm('app_filemanager.can_list_file'):
        return render_to_response('app_filemanager/noperm.html', context_instance=RequestContext(request,locals()))
    else: 
        user_name = request.user.id
        # 为publicprojects附加一个projects__count对象来获得每个project有几个File
        # 返回公开的项目的queryset
        allProjects = Project.allProjects.all().annotate(Count('projects'))
        recentUploadFile = File.projectFiles.all().order_by('-upload_date')[:4]
    return render_to_response('app_filemanager/listProject.html', context_instance=RequestContext(request,locals()))

def GlobleView(request):
    publicprojects = Project.publicProjects.all().annotate(Count('projects'))
    recentUploadFile = File.projectFiles.all().order_by('-upload_date')[:4]
    return {
        'publicprojects': publicprojects,
        'recentUploadFile': recentUploadFile,
    }
    
def ListAllProjectFileView(request):
    activePublicList = "active"
    allprojectfile = File.projectFiles.all().order_by('-upload_date')
    return render_to_response('app_filemanager/listAllProjectFile.html', context_instance=RequestContext(request,locals()))
def ListProjectFileView(request, project_id):
    activePublicList = "active"
    theproject = Project.publicProjects.get(id=project_id)
    projectFiles = File.projectFiles.filter(project = project_id).order_by('-upload_date')
    dict = {}
    for o in projectFiles:
        o.active_field = "active"
    return render_to_response('app_filemanager/listProjectFile.html', context_instance=RequestContext(request,locals()))

def ListPublicFileView(request):
    activePublicList = "active"
    publicFiles = File.publicFiles.all().order_by('-upload_date')
    return render_to_response('app_filemanager/listPublicFile.html', context_instance=RequestContext(request,locals()))

# -----------------------------detail-------------
def FileDetailView(request, file_id):
    file = get_object_or_404(File, pk=file_id)
    file_type=mimetypes.guess_type(file.file.url)[0]
    return render_to_response('app_filemanager/filedetail.html', context_instance=RequestContext(request,locals()))
def FileDetailView_no_edit(request, file_id):
    file = get_object_or_404(File, pk=file_id)
    file_type=mimetypes.guess_type(file.file.url)[0]
    return render_to_response('app_filemanager/filedetail_no_edit.html', context_instance=RequestContext(request,locals()))

def ProjectDetailView(request, project_id):
    project = get_object_or_404(Project, pk=project_id)
    return render_to_response('app_filemanager/projectdetail.html', context_instance=RequestContext(request,locals()))


@login_required
def DownloadView(request, file_id):
    x = get_object_or_404(File, pk=file_id)
    if request.user.id == 1:
        name = x.file.name.split('/').pop()
        wrapper=FileWrapper(x.file) 
        content_type=mimetypes.guess_type(x.file.url)
        response=HttpResponse(wrapper,content_type=content_type)
        response['Content-Length'] = x.file.size
        print sys.getdefaultencoding()
        response['Content-Disposition']="attachment;filename=%s" % str(name) 
        return response
    elif not (request.user.has_perm('app_filemanager.can_download_file') or request.user.id == x.uploader.id):
            return render_to_response('app_filemanager/noperm.html', context_instance=RequestContext(request,locals()))
    else:
        name = x.file.name.split('/').pop()
        wrapper=FileWrapper(x.file)
        content_type=mimetypes.guess_type(x.file.url)
        response=HttpResponse(wrapper,content_type=content_type)
        response['Content-Length'] = x.file.size
        print sys.getdefaultencoding()
        response['Content-Disposition']='attachment;filename=%s' % str(name)
        return response

def LogoutView(request):
    logout(request)
    return HttpResponseRedirect("/file")

@login_required
def UserProfileView(request):
    return render_to_response('app_filemanager/userprofile.html', context_instance=RequestContext(request,locals()))
# -------------------------------create
class ProjectCreateView(CreateView):
    model = Project
    success_url = '/file/list/project/'
# -------------------------------update
class FileUpdateView(UpdateView):
    model = File
    template_name_suffix = '_update_form'
    success_url = '/file/list/personal/'
    permission_required = 'app_filemanager.can_change_file'
    permission_fail_message = ('You don\'t have permission to change employee info.')
    form_class = FileForm
    def get_form_kwargs(self):
        kwargs = super(FileUpdateView, self).get_form_kwargs()
        kwargs.update({
            'user':self.request.user
        })
        return kwargs

    # 限制只能修改本人上传的文件
    def get_queryset(self):
        base_qs = super(FileUpdateView, self).get_queryset()
        return base_qs.filter(uploader=self.request.user)

class ProjectUpdateView(UpdateView):
    model = Project
    template_name_suffix = '_update_form'
    success_url = '/file/list/project/'
    permission_required = 'app_filemanager.can_change_file'
    permission_fail_message = ('You don\'t have permission to change employee info.')
    form_class = ProjectForm

class DeleteFileView(DeleteView):
    model = File
    success_url = '/file/list/personal/'

def SearchView(request):
    #if not request.user.has_perm('app_filemanager.can_see'):
    #    return render_to_response('app_filemanager/noperm.html', context_instance=RequestContext(request,locals()))
    #else:
    text = request.GET.get('searchtext', '')
    user_id = request.user.id
    #file = get_list_or_404(File,file__icontains=text, uploader=user_id)
    searchFiles = File.allFiles.filter(file__icontains=text)
    return render_to_response('app_filemanager/searchResult.html', context_instance=RequestContext(request,locals()))
"""
def SearchView(request):
    if not request.user.has_perm('app_filemanager.can_see'):

app_filemanager/templates/app_filemanager/download.html
{% extends "app_filemanager/index.html" %}

{% block index %}
download page
{% endblock %}

app_filemanager/templates/app_filemanager/file_confirm_delete.html
{% extends 'base.html' %}

{% block content_middle %}
<form action="" method="post">{% csrf_token %}
    <p>你确定你要删除 "{{ object }}"?</p>
    <input class='btn' type="submit" value="确定" />
</form>
{% endblock %}

app_filemanager/templates/app_filemanager/file_update_form.html
{% extends "base.html" %}
{% block content_middle %}
<form action="" method="post">{% csrf_token %}
        <li>
          <label for="id_project">{{ form.project.label }}</label>
          {{ form.project.errors }}</ul>
          {{ form.project }}
        </li>
        <li>
          <label for="id_tag">{{ form.tag.label }}</label>
          {{ form.tag.errors }}
          {{ form.tag }}
          <span class="helptext">{{ form.tag.help_text }}</span>
        <a href="/admin/app_filemanager/tag/add/" class="add-another" id="add_id_tag" onclick="return showAddAnotherPopup(this);"> <img src="/static/admin/img/icon_addlink.gif" width="10" height="10" alt="Add Another"/>    </a>
        </li>
        <li>
          <label for="id_group">{{ form.group.label }}</label>
          {{ form.group }}
          {{ form.group.errors }}
          <span class="helptext">{{ form.group.help_text }}</span>
        </li>
        <li>
          <label id="id_desc">{{ form.desc.label }}</label>
          {{ form.desc.errors }}
          {{ form.desc }}
          <span class="helptext">{{ form.desc.help_text }}</span>
        </li>
        <!--<li>
        <label for="id_file">{{ form.file.label }}</label>
                             {{ form.file }}
        <span class="helptext">{{ form.file.help_text }}</span>
        </li>-->
        <li>
          <label class="id_public">{{ form.public.label }}<label>
          {{ form.public }}
        </li>
    <input type="submit" class="btn btn-default" value="Update" />
</form>
<style type="text/css">
    ul.errorlist {
        margin: 0;
        padding: 0;
    }
    .errorlist li {
        background-color: red;
        color: white;
        display: block;
        font-size: 12px;
        margin: 0 0 3px;
        padding: 4px 5px;
    }
    .helptext {
        font-size: 10px !important;
        color: #999;
    }
    label {
        color: #0C3C26;
    }
</style>
{% endblock %}

app_filemanager/templates/app_filemanager/filedetail.html
{% extends "app_filemanager/index.html" %}

{% block content_middle %}
<dl class="dl-horizontal">
      <dt>文件名</dt>
      <dd>{{file.file.name}}</dd>
      <dt>大小</dt>
      <dd><kbd>{{ file.file.size|filesizeformat }}</kbd></h1>
      <dt>类型</dt>
      <dd>{{ file_type|default_if_none:"未识别"}}</dd>
      <dt>上传日期</dt>
      <dd>{{ file.upload_date }}</dd>
      <dt>上次修改</dt>
      <dd>{{ file.change_date }}</dd>
      <dt>描述</dt>
      <dd>{{ file.desc }}</dd>
      <dt>操作</dt>
      <dd><a href="{% url 'file:download' file.id %}" class="btn btn-default" role="button">下载</a>
	  <a href="{% url 'file:deletefile' file.id %}" class="btn btn-default" role="button">删除</a>
	  <a href="{% url 'file:fileupdate' file.id %}" class="btn btn-default" role="button">编辑</a>
<!--	  <a href="{% url 'file:listPersonal' %}" class="btn btn-default" role="button">返回</a>-->
      </dd>

</dl>
{% endblock %}

app_filemanager/templates/app_filemanager/filedetail_no_edit.html
{% extends "app_filemanager/index.html" %}

{% block content_middle %}
<dl class="dl-horizontal">
      <dt>文件名</dt>
      <dd>{{file.file.name}}</dd>
      <dt>大小</dt>
      <dd><kbd>{{ file.file.size|filesizeformat }}</kbd></h1>
      <dt>类型</dt>
      <dd>{{ file_type|default_if_none:"未识别"}}</dd>
      <dt>上传日期</dt>
      <dd>{{ file.upload_date }}</dd>
      <dt>上次修改</dt>
      <dd>{{ file.change_date }}</dd>
      <dt>描述</dt>
      <dd>{{ file.desc }}</dd>
      <dt>操作</dt>
      <dd><a href="{% url 'file:download' file.id %}" class="btn btn-default" role="button">下载</a>
<!--	  <a href="{% url 'file:listPersonal' %}" class="btn btn-default" role="button">返回</a>-->
      </dd>

</dl>
{% endblock %}

app_filemanager/templates/app_filemanager/listProject.html
{% extends "base.html" %}
{% block script %}

{% endblock %}
{% block title %}
<title>项目文档</title>
{% endblock %}

{% block content_left %}
<i class="oneofthree">项目:</i>
<hr>
	<input id="search" class="form-control"  name="search" placeholder="项目名或者文档数" type="text" data-toggle="hideseek" data-list=".list-group">
	<br>
	<ul class="list-group">
	{% for p in publicprojects %}
	<!--
		<div class="list-group-item" project_name="{{ p.name }}" file_count="{{ p.projects__count }}">
		  <span class="badge">{{ p.projects__count }}</span>
		  <abbr title="{{ p.desc }}"><a href="{% url 'file:listProjectfile' p.id %}">{{ p.name }}</a></abbr>
		</div>
	-->
	{% if p.projects__count != 0 %}
	<a href="{% url 'file:listProjectfile' p.id %}" class="list-group-item">
		<span class="badge">{{ p.projects__count }}</span>
		<small>{{ p.name }}</small>
	</a>
	{% endif %}
	{% endfor %}
	</ul>
{% endblock %}

{% block content_middle %}
<i class="oneofthree">项目管理:</i>
<hr>
							{% if allProjects %}
									    <table id='file' class="table table-hover table-condensed table-striped">
										<thead>
											<tr>
												<th>
													#
												</th>
												<th>
													项目名
												</th>
												<th>
													添加时间
												</th>
												<th>
													公开	
												</th>
												<th>
													操作 
												</th>


											</tr>
										</thead>
										<tbody>
										{% for p in allProjects %}
											<tr class="article">
												<td>
													{{ forloop.counter }}
												</td>
												<td class="has_desc">
													{{ p.name }}
													<div class="description" style="display:none"><h3><i>{{ p.desc|default:"无描述" }}</i></h3></div>
												</td>
												<td>
													{{ p.add_date|timesince }}&nbsp;前
												</td>
												<td>
													{{ p.public|default:"否" }}
												</td>
												<td>
													<a href="{% url "file:projectdetail" p.id %}">详情</a>	
									
												</td>
											</tr>
										{% endfor %}
									</table>
							{% else %}
								No project in database.
							{% endif %}
<a href="{% url 'file:createproject' %}" class="btn btn-success">添加</a>
{% endblock %}

{% block content_right %}
<div>
<i class="oneofthree">最近上传:</i>
<hr>
{% for f in recentUploadFile %}
<address>
  <strong style="word-break:break-all">{{ f.file.name }}</strong><br>
  所属项目：{{ f.project }}<br>
  上传时间：{{ f.upload_date }}<br>
  <abbr title="Permited"><a href="{% url "file:download" f.id %}">Download</a></abbr>&nbsp;&nbsp;<!--<abbr title="Permited"><a href="{% url "file:filedetail" f.id %}">Detail</a></abbr>-->
</address>
{% endfor %}
</div>
{% endblock %}
{% block javascript %}
<script type="text/javascript" src="/static/js/dataTables_yuan.js"></script>
{% endblock %}

app_filemanager/templates/app_filemanager/noperm.html
{% extends "app_filemanager/index.html" %}

{% block content_middle %}
<h1>{{ username }}has no perms</h1>
{% endblock %}

app_filemanager/templates/app_filemanager/searchResult.html
{% extends "app_filemanager/listProject.html" %}

{% block content_middle %}
<h2>搜索结果：{{ text }}</h2>
<hr>
							{% if searchFiles %}
									    <table class="table table-hover table-condensed table-striped">
										<thead>
											<tr>
												<th>
												</th>
												<th>
													文件名
												</th>
												<th>
													上传于
												</th>
												<th>
													项目
												</th>
 												<th>
													操作 
												</th>


											</tr>
										</thead>
										<tbody>
							    {% for file in searchFiles %}
											<tr>
												<td>
													{{ forloop.counter }}
												</td>
												<td>
													{{ file.file.name }}
												</td>
												<td>
													{{ file.upload_date|timesince }}&nbsp;前
												</td>
												<td>
													{{ file.project|default:"无" }}
												</td>
												<td>
													<a href="{% url 'file:filedetail' file.id %}">更多</a>
													<a href="{% url 'file:listProject' %}">返回</a>
												</td>


											</tr>
							    {% endfor %}
										</tbody>
							</table>
{% endif %}					
{% endblock %}

app_filemanager/templates/app_filemanager/upload.html
{% extends "base.html" %}
{% block content_left %}
<div class="alert alert-success alert-dismissable">
	 <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
				 <strong>注意!</strong>只有在项目为空，且没选择公开的情况下，文件才属于个人可见 
</div>
{% endblock %}
{% block content_middle %}
<!--<div class="alert alert-success alert-dismissable">
  <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
    提示，上传文件限制20M以下
</div>-->
{% if form.is_multipart %}
    <form enctype="multipart/form-data" method="post">
{% else %}
    <form method="post">
{% endif %}
{% csrf_token %}

<div class="form-group">
	<li>
	  <label for="id_project">{{ form.project.label }}</label><a type="button" class="btn" href="{% url "file:listProject" %}">项目管理</a>
	  {{ form.project.errors }}</ul>
	  {{ form.project }}
	</li>
	<li>
	  <label for="id_tag">{{ form.tag.label }}</label>
	  {{ form.tag.errors }}
	  {{ form.tag }}
	  <span class="helptext">{{ form.tag.help_text }}</span>
	<a href="/admin/app_filemanager/tag/add/" class="add-another" id="add_id_tag" onclick="return showAddAnotherPopup(this);"> <img src="/static/admin/img/icon_addlink.gif" width="10" height="10" alt="Add Another"/>    </a>
	</li>
	<li>
	  <label for="id_group">{{ form.group.label }}</label>
	  {{ form.group }}
	  {{ form.group.errors }}
	  <span class="helptext">{{ form.group.help_text }}</span>
	</li>
	<li>
	  <label id="id_desc">{{ form.desc.label }}</label>
	  {{ form.desc.errors }}
	  {{ form.desc }}
	  <span class="helptext">{{ form.desc.help_text }}</span>
	</li>
	<li>
	<label for="id_file">{{ form.file.label }}</label>
			     {{ form.file }}
	<span class="helptext">{{ form.file.help_text }}</span>
	</li>
	<li>
	  <label class="id_public">{{ form.public.label }}<label>
	  {{ form.public }}
	</li>
	---------------------------
</div>
<style type="text/css">
    ul.errorlist {
        margin: 0;
        padding: 0;
    }
    .errorlist li {
        background-color: red;
        color: white;
        display: block;
        font-size: 12px;
        margin: 0 0 3px;
        padding: 4px 5px;
    }
    .helptext {
        font-size: 10px !important;
        color: #999;
    }
    label {
        color: #0C3C26;
    }
</style>

<button type="submit" class="btn btn-default">Submit</button>
</form>
{% endblock %}