app_filemanager/urls.py
#coding=utf-8
from django.conf.urls import patterns,url
from app_filemanager import views


urlpatterns=patterns('',
    url(r'^$',views.IndexView, name='index'),
    # create file & project
    url(r'^create/project/$', views.ProjectCreateView.as_view(), name='createproject'),
    url(r'^upload/$', views.UploadView, name='upload'), 
    # list file & project
    url(r'^list/personal/$', views.ListPersonalView, name='listPersonal'),
    url(r'^list/project/$', views.ListProjectView, name='listProject'),
    url(r'^list/allprojectfile/$', views.ListAllProjectFileView, name='listAllProjectFile'),
    url(r'^list/allpublicfile/$', views.ListPublicFileView, name='listPublicFile'),
    # detail file & project
    url(r'^detail/fileid=(?P<file_id>\d+)/$', views.FileDetailView, name='filedetail'), 
    url(r'^detail/fileid_no_edit=(?P<file_id>\d+)/$', views.FileDetailView_no_edit, name='filedetail_no_edit'), 
    url(r'^detail/projectid=(?P<project_id>\d+)/$', views.ProjectDetailView, name='projectdetail'),
    # update file & project
    url(r'^file/update/fileid=(?P<pk>\d+)/$', views.FileUpdateView.as_view(), name='fileupdate'),
    url(r'^project/update/projectid=(?P<pk>\d+)/$', views.ProjectUpdateView.as_view(), name='projectupdate'),
    # list file of each project
    url(r'^list/projectfile/projectid=(?P<project_id>\d+)$', views.ListProjectFileView, name='listProjectfile'),
    # down file
    url(r'^download/fileid=(?P<file_id>\d+)/$',views.DownloadView,name='download'), 
    # delete file
    url(r'^delete/fileid=(?P<pk>\d+)/$', views.DeleteFileView.as_view(), name='deletefile'),
    url(r'search/$',views.SearchView, name='search'), 
)

xtyw/urls.py
from django.conf.urls import patterns, include, url
from app_filemanager import views
# -------------------------------------------------------
from django.contrib import admin
from app_filemanager.api import ProjectResource
entry_resource = ProjectResource()
# -------------------------------------------------------
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    url(r'^$', views.IndexView, name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^api/', include(entry_resource.urls)),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^file/',include('app_filemanager.urls', namespace="file")),
    url(r'^accounts/login/$', 'django.contrib.auth.views.login', name="login"),
    url(r'^accounts/logout$', views.LogoutView, name="logout"),
    url(r'^accounts/profile/$', views.UserProfileView),
)

xtyw/templates/base.html
<!DOCTYPE html>
<html lang="zh-cn">
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="/static/css/bootstrap.min.css" >
<link rel="stylesheet" href="/static/js/bootstrap-datetimepicker-master/css/bootstrap-datetimepicker.min.css">
<link rel="stylesheet" href="/static/css/devops.css" >
<link rel="stylesheet" href="/static/css/jquery.dataTables.css" >

{% block css %} {% endblock %}
{% block script %} {% endblock %}


<!--[if lt IE 9]>
      <script src="http://cdn.bootcss.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="http://cdn.bootcss.com/respond.js/1.4.2/respond.min.js"></script>
<![endif]-->
    
{% block title %}
<title>主页</title>
{% endblock %}
</head>

<body>
<div class="container-fluid">
  <div class="row clearfix">
    <div class="col-md-12 culumn">
      <div class="row clearfix">
        {% block content_span12 %}
        <div class="col-md-2 column left_space">
            {% block content_left %}
            {% endblock %}
        </div>

        <div class="col-md-8 column middle_space" >
            {% block content_middle %}
            {% endblock %}
        </div>
        <div class="col-md-2 column right_space">
            {% block content_right %}
            {% endblock %}
        </div>
        {% endblock %}
<!--以下为文档管理插件-->
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
				<div class="navbar-header">
					 <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1"> <span class="sr-only">Toggle navigation</span><span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span></button> <a class="navbar-brand" href="#">文档库</a>
				</div>
				
				<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
					<ul class="nav navbar-nav">
						<li class="{{ activeIndex }}">
							<a href="{% url 'file:index' %}">主页{{ fuck }}</a>
						</li>
						<li class="{{ activeUpload }}">
							<a href="{% url 'file:upload' %}">上传</a>
						</li>
                                                <li class="{{ activePersonalList }}">
							<a href="{% url 'file:listPersonal' %}">个人上传</a>
						</li>
						<li class="dropdown {{ activePublicList }}">
							 <a href="#" class="dropdown-toggle" data-toggle="dropdown">公共<strong class="caret"></strong></a>
							<ul class="dropdown-menu">
								<li>
									<a href="{% url 'file:listPublicFile' %}">共享文档</a>
								</li>
								<li>
									<a href="{% url 'file:listAllProjectFile' %}">项目文档</a>
								</li>
								<li class="divider">
								</li>
								<li>
									<a href="{% url "file:index" %}">数量统计</a>
								</li>
								<li class="divider">
								</li>
								<li>
									<a href="{% url 'file:listProject' %}">项目管理</a>
								</li>
							</ul>
						</li>
					</ul>
					<form action="{% url "file:search" %}" class="navbar-form navbar-left" role="search">
						<div class="form-group">
							<input placeholder="搜索你的文件"  type="text" class="form-control" name="searchtext" />
						</div> <button type='submit' class="btn btn-default">搜索</button>
					</form>
					<ul class="nav navbar-nav navbar-right">
						{% if user.is_authenticated %}
						<li>
							<a href="#">{{ user.first_name|default:"无名" }}</a>
						</li>
						<li>
							<a href="{% url 'logout' %}">注销</a>
						</li>
						{% else %}
						<li>
							<a href="{% url 'login' %}">登陆</a>
						</li>
						{% endif %}
					</ul>
				</div>
				
			</nav>
      </div>
    </div>
  </div>
</div>

<script type="text/javascript" src="/static/js/jquery.min.js"></script>
<script type="text/javascript" src="/static/js/bootstrap.min.js"></script>
<script type="text/javascript" src="/static/js/bootstrap-datetimepicker-master/js/bootstrap-datetimepicker.min.js"></script>
<script type="text/javascript" src="/static/js/bootstrap-datetimepicker-master/js/locales/bootstrap-datetimepicker.zh-CN.js" charset="UTF-8"></script>
<script type="text/javascript" src="/static/js/jquery.validate.js"></script>
<script type="text/javascript" src="/static/js/messages_zh.min.js"></script>
<script type="text/javascript" src="/static/js/ylzdc.js"></script>
<script src="/static/admin/js/admin/RelatedObjectLookups.js" type="text/javascript"></script>
<script type="text/javascript" src="/static/js/HideSeek-master/jquery.hideseek.min.js"></script>
<script type="text/javascript" src="/static/js/jquery.dataTables.js"></script>
{% block javascript %}
{% endblock %}

</body>
</html>

{% block scripts %} {% endblock %}

xtyw/templates/base_backup.html
<!DOCTYPE html>
<html lang="zh-cn">
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="/static/css/bootstrap.min.css" >
<link rel="stylesheet" href="/static/css/devops.css" >
<link rel="stylesheet" href="/static/js/bootstrap-datetimepicker-master/css/bootstrap-datetimepicker.min.css">
<script src="http://cdn.bootcss.com/jquery/1.11.1/jquery.min.js"></script>
<script type="text/javascript" src="/static/js/bootstrap.min.js"></script>
<script type="text/javascript" src="/static/js/bootstrap-datetimepicker-master/js/bootstrap-datetimepicker.min.js"></script>
<script type="text/javascript" src="/static/js/bootstrap-datetimepicker-master/js/locales/bootstrap-datetimepicker.zh-CN.js" charset="UTF-8"></script>
<script type="text/javascript" src="/static/js/jquery.validate.js"></script>
<script type="text/javascript" src="/static/js/messages_zh.min.js"></script>
<script type="text/javascript" src="/static/js/ylzdc.js"></script>
{% block css %} {% endblock %}


<!--[if lt IE 9]>
      <script src="http://cdn.bootcss.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="http://cdn.bootcss.com/respond.js/1.4.2/respond.min.js"></script>
<![endif]-->
    
{% block title %}
<title>主页</title>
{% endblock %}
</head>

<body>
<!--header-->
<nav class="navbar navbar-default navbar-fixed-top navbar-inverse" role="navigation">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand brand" href="#"></a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">首页</a></li>
        <li><a href="#">解决方案</a></li>
        
         <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">服务<span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="#">集团服务</a></li>
            <li class="divider"></li>
            <li><a href="#">对分公司服务</a></li>
            <li class="divider"></li>
            <li><a href="#">对外业务</a></li>
          </ul>
        </li>
        
       
        
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">数据中心<span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="#">维保管理</a></li>
             <li class="divider"></li>
            <li><a href="#">资源管理</a></li>
            <li class="divider"></li>
            <li><a href="#">配置管理</a></li>
            <li class="divider"></li>
            <li><a href="#">监控管理</a></li>
          </ul>
        </li>
        
        <li><a href="#">测试平台</a></li>
        <li><a href="#">统计报表</a></li>
        <li><a href="#">系统管理</a></li>
       
      </ul>
   </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
<!-- /container --> 



<div class="container">
  <div class="col-md-12" style="padding-bottom: 65px;">
	{% block content_span12 %}

        <div class="col-md-2">
	    {% block content_left %}
	    {% endblock %}
        </div>
	    
	<div class="col-md-8">
	    {% block content_middle %}
	    {% endblock %}
	</div>
	<div class="col-md-2">
	    {% block content_right %}
	    {% endblock %}
	</div>
	{% endblock %}
  </div>
</div>
<!--footer
<div class="row" id="footer">
  <div class="col-md-12">
  <footer>
  <ul class="list-inline">
    <li><a href="javascript:">联系我们 |</a></li>
    <li><a href="javascript:">在线客服 |</a></li>
    <li><a href="javascript:">网站导航>></a></li>
  </ul>
  <div>易联众 &copy;2010 ylzinfo.com&nbsp;&nbsp;All rights reserved &nbsp;&nbsp;闽ICP备05020898</div>
  <address>
  地址：厦门思明软件园观日路18号502&nbsp;&nbsp; <abbr title="Phone">电话：</abbr>0592-2517033&nbsp;&nbsp; <a href="mailto:#">传真：</a>0592-2517008
  </address>
  </footer>
 </div>
</div>
-->
</body>
</html>

{% block scripts %} {% endblock %}